version: '3.4'

services:
  backend:
    build:
      context: ./InsuranceApi
      dockerfile: Dockerfile
    ports:
      - "5064:80"

  frontend:
    build:
      context: ./vehicle-insurance-app
      dockerfile: Dockerfile
    ports:
      - "3001:80"
